### ISSUE TITLE
Fail to install learn2learn module

### ISSUE THREAD

**Issue by 688spiderbin** [HICAI-ZJU/GS-Meta#1]
Hello, 
I have installed  torch=1.7 torch_geometric=1.6.3 in win10  successfully following your instructions, but failed to install learn2learn module,  could you help me to fix it? Thanks 
![image](https://github.com/HICAI-ZJU/GS-Meta/assets/62921113/057f3399-e5ed-40e1-9f25-fcf864a79ab0)

**Comment by toooooodo** [comment]
Thank you for your interest in our work. Our experiments were done on a Linux server. This seems to be a problem within the learn2learn module. Could you try to test it on a Linux server? Or try installing different learn2learn release packages.
