### ISSUE TITLE
question

### ISSUE THREAD

**Issue by mch33** [HICAI-ZJU/GS-Meta#2]
hello, I have installed all, but any mistakes are still returned, what do I need to do?
D:\Users\anaconda\python.exe E:/知识/GS-Meta-init/run.py
Traceback (most recent call last):
  File "E:\知识\GS-Meta-init\run.py", line 65, in <module>
    main()
  File "E:\知识\GS-Meta-init\run.py", line 55, in main
    torch.cuda.set_device(int(args.gpu))
  File "D:\Users\anaconda\lib\site-packages\torch\cuda\__init__.py", line 404, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
![8e2e0f653286329ce414a74dcea0069](https://github.com/HICAI-ZJU/GS-Meta/assets/131531268/f5065cae-7767-4fe8-9ec6-32b8862a5c25)

**Comment by toooooodo** [comment]
Hi, this may help you. https://github.com/pytorch/pytorch/issues/33655
If your server does not support GPU, please set the `gpu` parameter in https://github.com/HICAI-ZJU/GS-Meta/blob/main/args_parser.py#L13 to -1 to use CPU.
